### ISSUE TITLE
deflate/inflate bug

### ISSUE THREAD

**Issue by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [vurtun/lib#36]
compiled https://github.com/vurtun/lib/blob/master/tests/defl_test.c with latest version of https://github.com/vurtun/lib/blob/master/sdefl.h and https://github.com/vurtun/lib/blob/master/sinfl.h and for the test i passed a file that contain some 250kb of text as argument and it failed with error error: 183449:183450 !
running diff error.bin and my text file it shows that 1 character is missing from the decompressed file (error.bin) which is the last character.
and that because it didnt end with a newline, so after adding a newline to my text, it runs fine without errors... however adding two more newlines generate an error error: 183451:183452 ! and again error.bin is missing one newline character from the original text.
so it seems like some alignment issues with sinfl.h, and this issue happens only after this commit (tested with earlier version today and it was fine) https://github.com/vurtun/lib/commit/8252ab92429f3b14ce792f052ad821c84357bf92

p.s. sorry for the long user name, i had to create github account report this issue, and i really hate it when developers dont put their email to contact them by mail. (beside that i never used github or any git based service or anything relaying on git variants)
p.p.s. i never used your defalte and inflate headers, actually i just discovered them after browsing your repository, and i know you are the creator of nuklear, which is something i use for quite some time.

**Comment by vurtun** [comment]
Thanks for the issue. Should be fixed in commit: 71382a1d14dad58219e7f6634d2381fa30dab175. Stupid off by one bug.
