### ISSUE TITLE
`sdefl`: Possible corrupt DEFLATE stream generation under very specific circumstances

### ISSUE THREAD

**Issue by raysan5** [vurtun/lib#40]
Recently I found a very weird issue while generating PNG files with my [`rpng`](https://github.com/raysan5/rpng) library that uses `sdefl` for deflate stream generation.

It worked very well with most image file generation but I found a very specific issue while generating a 512x512 image file. The generated file is somewhat corrupted and can not be opened. I tried with many other sizes and everything works fine. 

I attach a .zip containing two files, one generated with [`stb_image_write`](https://github.com/nothings/stb/blob/master/stb_image_write.h) and one generated with `rpng`: [rfxgen_512x512.zip](https://github.com/vurtun/lib/files/11590025/rfxgen_512x512.zip)

Actually, some image viewers can decompress the `rpng` generated image but others can't. `stbiw` generated images work in all cases.

I tried to load `rpng` image with `stb_image` loader and I narrowed the issue to [one specific line](https://github.com/nothings/stb/blob/master/stb_image.h#L4314):
```c
    if (z >= 286) return stbi__err("bad huffman code","Corrupt PNG"); // per DEFLATE, length codes 286 and 287 must not appear in compressed data
```
Located in function: `static int stbi__parse_huffman_block(stbi__zbuf *a)`

It seems the `sdefl` stream generates a `z = 286` value under very specific circumstances.

I also reviewed the image data PNG filtering on `rpng` side but I couldn't find any issue in there...

EDIT 1: In case it could be useful, the stream to be compressed has a size of `(512x512x4 + 512) = 1049088 bytes`, it is the scanlines size (512 pixels width x 4 bytes/pixel) with the additional pre-filter byte (+1) multiplied by the image height (512).

EDIT 2: Note the problematic image can be read back correctly using `rpng`, despite being reported as corrupted by `stbi` and some image viewers.

EDIT 3: `rpng` image can read by Paint.NET but I noticed the last scanline of the image is completely blank, maybe the point were it fails decompression?

**Comment by raysan5** [comment]
Adding source files for testing: [image_512x512.raw.zip](https://github.com/vurtun/lib/files/11592603/image_512x512.raw.zip)

The .zip includes two files:

 - `image_512x512.raw`: The actual image raw data, it's a 512x512x4 bytes file
 - `image_512x512_data_filtered.raw`: The image after appending the PNG 1 byte filter info to every scanline, (512x512x4 + 512 bytes) file. This is the actual data that goes into the compressor (`data_filtered`). Here the code used:
```c
    // Compress filtered image data and generate a valid zlib stream
    struct sdefl *sde = RPNG_CALLOC(sizeof(struct sdefl), 1);
    int bounds = sdefl_bound(data_size_filtered);
    unsigned char *comp_data = (unsigned char *)RPNG_CALLOC(bounds, 1);
    int comp_data_size = zsdeflate(sde, comp_data, data_filtered, data_size_filtered, 8);   // Compression level 8, same as stbwi
    RPNG_FREE(data_filtered);
    RPNG_FREE(sde);
```
The resulting `comp_data` goes directly to the PNG IDAT chunk.

**Comment by vurtun** [comment]
Fixed issue in commit: 6df154369519d00da97b97eff3bfef6863bf7a41

**Comment by raysan5** [comment]
Tested the fix and now image with size 512x512 works as expected, it can be saved and loaded with all tested applications, just to clarify testing applications:

 - Windows explorer thumbnails
 - Paint.NET
 - XnView MP
 - Photoshop CS5
 - rTexViewer (using stb_image)

But now another size presents issues, the 16x16 image size. Some applications can't load it, it becomes corrupted with others and it works with others. Here the details:

 - Windows explorer thumbnails -> Corrupted, blank pixels at the bottom:
![image](https://github.com/vurtun/lib/assets/5766837/cda9e978-ae6e-4641-84bc-f2083e3458ba)
 - Paint.NET -> Corrupted, blank pixels at the bottom
 - XnView -> Corrupted thumbnail and error at loading the full image
 - Photoshop CS5 -> Error, can not be loaded
 - rTexViewer (using stb_image) -> Works ok

I'm attaching a .zip file ([image_16x16_issue.zip](https://github.com/vurtun/lib/files/11594176/image_16x16_issue.zip)) containing:
 - `image_16x16_issue.png`: Generated image file a .png
 - `image_16x16_data_filtered.raw`: Filtered png data, ready for the compressor (`data_filtered`).

Sorry for the inconvenience... :(

**Comment by RandyGaul** [comment]
Ray, just wanted to say I thought your opened issue here was very professional! And also wanted to note how cool it was that Micha worked on a fix so quickly. Fan of both your works :)

**Comment by vurtun** [comment]
Thank you Randy. Absolutely agree with you. Perfect example of a very very good issue and problem description. Made it a lot easier to find the problem. Just to clarify since it may not be obvious but we are in DMs on twitter so that is the reason why I didn't write much here.

**Comment by vurtun** [comment]
Pushed another commit: 57351fcf8dea218e6bb3d24908b8087c7dcc3c1a that seems to fix the issue. Ray will test it tomorrow a bit more but for now it seems to work at least

**Comment by raysan5** [comment]
I'm still testing it but for now it seems everything works perfectly!

Thanks again for the super-fast response and multi-fix! You are the best! :D
