### ISSUE TITLE
Integer overflow in sdefl_bound

### ISSUE THREAD

**Issue by zeux** [vurtun/lib#41]
This computation:

```
  int a = 128 + (len * 110) / 100;
```

overflows when len is more than ~19 MB. I assume `int a = 128 + len + len / 10;` would work better here?

**Comment by vurtun** [comment]
Thank you for the issue. Sorry it took a bit longer to look into it. The issue should now be fixed with commit d41cf94679443efc14174cac103c9c15bb115860. Instead of reserving more space I decided to instead cap the maximum output making use of uncompresssed blocks in deflate.
