### ISSUE TITLE
[sdefl] crash on `sdefl_compr()` after last update

### ISSUE THREAD

**Issue by raysan5** [vurtun/lib#45]
Today I tried the latest update and I got a crash when trying to compress some data.

It happens when calling `zdeflate()`, I attach the crash line and call-stack for convenience. It happens for different images at different sizes, input data is valid and it worked with previous implementation. I had no problem with the updated `sinfl`. 

![image](https://github.com/vurtun/lib/assets/5766837/a802d76e-e262-49b7-b714-7e50d105fdab)

**Comment by vurtun** [comment]
Hey thanks Ray. Will take a look this evening

**Comment by raysan5** [comment]
I reviewed initialization on my side, just in case, it seems correct:
```c
    // Compress filtered image data and generate a valid zlib stream
    struct sdefl *sde = RPNG_CALLOC(1, sizeof(struct sdefl));
    int bounds = sdefl_bound(data_filtered_size);
    unsigned char *comp_data = (unsigned char *)RPNG_CALLOC(bounds, 1);
    int comp_data_size = zsdeflate(sde, comp_data, data_filtered, data_filtered_size, 8);   // Compression level 8, same as stbiw
    RPNG_FREE(data_filtered);
    RPNG_FREE(sde);
```

**Comment by vurtun** [comment]
Ok that is really strange. `lit` is a static array so should always be allocated: `unsigned lit[SDEFL_SYM_MAX];`. I changed the size of `struct sdefl` because I had someone hit the maximum number of sequences per block.

**Comment by raysan5** [comment]
@vurtun Sorry, I'm afraid it was my fault. After long review issue was on my side, `sdefl` implementation is added to raylib and also to `rpng` to be used standalone and being completely portable, `rpng` implementation was disabled (to use raylib one) BUT it was not updated and definitions visible, so, my tool was using data definitions from old version in `rpng` but using `raylib` new implementation... My fault, already fixed and working as expected.

Sorry for the inconvenience...
